-- Create table
create table JOB51
(
  id           VARCHAR2(32) not null,
  code         VARCHAR2(12) not null,
  name         VARCHAR2(200),
  addr         VARCHAR2(32),
  salary       VARCHAR2(32),
  company      VARCHAR2(100),
  company_info VARCHAR2(150),
  year         VARCHAR2(32),
  education    VARCHAR2(32),
  num          VARCHAR2(20),
  release      VARCHAR2(10),
  language     VARCHAR2(32),
  type         VARCHAR2(100),
  welfare      VARCHAR2(150),
  jbdetail     VARCHAR2(4000),
  addr_detail  VARCHAR2(200)
) tablespace USERS;
-- Create/Recreate primary, unique and foreign key constraints
alter table JOB51
  add primary key (ID)
  using index
  tablespace USERS;

  CREATE TABLE "WKAI"."JOB51INFOPAGE"
   (	"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE PRIMARY KEY,
	"PAGEID" VARCHAR2(20 BYTE),
	"URL" VARCHAR2(200 BYTE),
	"DOWNFLAG" VARCHAR2(1 BYTE),
	"LOCALPATH" VARCHAR2(100 BYTE),
	"ANALYFLAG" VARCHAR2(1 BYTE)
   );

  CREATE TABLE "WKAI"."JOB51LISTPAGE"
   (	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE PRIMARY KEY,
	"URL" VARCHAR2(400 BYTE),
	"DOWNFLAG" VARCHAR2(1 BYTE),
	"LOCALPATH" VARCHAR2(50 BYTE),
	"ANALYFLAG" VARCHAR2(1 BYTE),
	"NUM" NUMBER(5,0)
   ) ;

  CREATE TABLE "WKAI"."JOB51"
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE PRIMARY KEY ,
	"CODE" VARCHAR2(12 BYTE) NOT NULL ENABLE,
	"NAME" VARCHAR2(200 BYTE),
	"ADDR" VARCHAR2(32 BYTE),
	"SALARY" VARCHAR2(32 BYTE),
	"COMPANY" VARCHAR2(100 BYTE),
	"COMPANY_INFO" VARCHAR2(150 BYTE),
	"YEAR" VARCHAR2(32 BYTE),
	"EDUCATION" VARCHAR2(32 BYTE),
	"NUM" VARCHAR2(20 BYTE),
	"RELEASE" VARCHAR2(10 BYTE),
	"LANGUAGE" VARCHAR2(32 BYTE),
	"TYPE" VARCHAR2(100 BYTE),
	"WELFARE" VARCHAR2(150 BYTE),
	"JBDETAIL" VARCHAR2(4000 BYTE),
	"ADDR_DETAIL" VARCHAR2(200 BYTE),
   )  ;

